# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: false
  branches:
    include:
    - master
    - release-*

variables:
  branch: $[ coalesce(variables['system.PullRequest.TargetBranch'], variables['build.SourceBranchName']) ]

pool:
  vmImage: ubuntu-16.04
container:
  image: sykesm/fabric-protos:0.2

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- script: |
    set -eu -o pipefail
    prototool lint
    [ -d build/fabric-protos-go/.git ] || git clone https://github.com/hyperledger/fabric-protos-go.git build/fabric-protos-go
    (
        cd build/fabric-protos-go
        git show-branch $(branch) > /dev/null 2>&1 || git branch $(branch)
        git checkout $(branch)
        if git ls-remote --heads --exit-code origin $(branch); then
            git pull origin $(branch)
        fi
    )
    ci/cleanup_generated.sh build/fabric-protos-go
    ci/compile_go_protos.sh
    cd build/fabric-protos-go
    go mod tidy
    go build ./...
    git diff --color

- template: merge-forward.yml
  parameters:
    repo: fabric-protos-go
    branch: $(branch)
    deploy_key: fabric-protos-go-deploy.key
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6oJcGtQmLT+uDIzMzkUpNiHVTFVthEOhHRamQ/z7k9+peQSXoI5c2zd6mMgygo2G+U/NrphQRAAU5ToxfQMV/B/wWKisCXr1F5DrNfBfSh127nHptZZDJR/PDEHbx3lkARZF9dlK4SsFofwd51uHc9nPdK54pSmEcKI62By4lQPIIcbumoviAbUpEkTdEoPz+VBUYTdqfSBfBfS5CS/L/Xl6aUdPbe4jtxZ+grMX93f3+itxGsQehnIwSNWkAENcMa8np/sMKVs3ER0GxgGbfDOMZCxYBPOuleUb7h/+N1IDsB83cIZ89gHDUAsrrYLmVlLD8I/dMK3vIP8/iPHH8SrJvjxbj+B86BKAKTFXtA8mOcy2WxBoPiIVWwNYCufh4sDeB/H/OM/cmISaYv7l+EHGTU3/LBHD3YGaBvrptQN9hMjSS0Z1wGg1svMEt3kNwNE44RNo1eDb+fnkoXm5D3NNv4ELhSkYS4OKGoD3FQtoOs5G6LMHXqEB0M7kVngv4SX5FIPVbnGBLubi8bfgNR+CN4xMDWYk+rPk3DmkHbs6DV+yPhQUvtbSOhIH2C12R288onaEc3Lr67c53AlC1B/Zne7ZSBKIvE6jZzwIcH/qbICyX86yTvxUMNOUEVqgoUSxN3yjZVtQAMke4sPOka087IL+ed67qrhhAviSnpw== fabric-build@hyperledger.org
