name: "Security vulnerability scan"

on:
  schedule:
    - cron: "20 02 * * *"
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: '1.22'

jobs:
  go-apiv1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false
      - name: Scan
        run: make -f Makefile.apiv1 scan-go

  go-apiv2:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false
      - name: Scan
        run: make scan-go

  node:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Scan
        run: make scan-node

  java:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Scan
        run: make scan-java
